-- MySQL Script generated by MySQL Workbench
-- 07/15/15 22:02:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotel` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `hotel` ;

-- -----------------------------------------------------
-- Table `hotel`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`usuarios` (
  `idusuarios` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tipoIdentificacion` VARCHAR(5) NOT NULL COMMENT '',
  `identificacion` INT NOT NULL COMMENT '',
  `nombres` VARCHAR(45) NOT NULL COMMENT '',
  `apellidos` VARCHAR(45) NOT NULL COMMENT '',
  `telefono` INT NOT NULL COMMENT '',
  `direccion` VARCHAR(45) NOT NULL COMMENT '',
  `fechaNacimiento` DATE NOT NULL COMMENT '',
  `usrLogin` VARCHAR(45) NOT NULL COMMENT '',
  `passLogin` VARCHAR(45) NOT NULL COMMENT '',
  `tipo` ENUM('Administrador', 'Cliente') NOT NULL COMMENT '',
  `estado` ENUM('Activo', 'Inactivo') NOT NULL COMMENT '',
  PRIMARY KEY (`idusuarios`)  COMMENT '',
  UNIQUE INDEX `idusuarios_UNIQUE` (`idusuarios` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`habitaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`habitaciones` (
  `idhabitaciones` INT NOT NULL COMMENT '',
  `numero` INT NOT NULL COMMENT '',
  `tipo` ENUM('Sencilla', 'Doble') NOT NULL COMMENT '',
  `foto` VARCHAR(40) NOT NULL COMMENT '',
  `estado` ENUM('Reservada', 'Disponible', 'Fuera de Servicio') NOT NULL COMMENT '',
  PRIMARY KEY (`idhabitaciones`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`reservas` (
  `idreservas` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fechaIngreso` DATETIME NOT NULL COMMENT '',
  `nDias` INT NOT NULL COMMENT '',
  `valorReserva` INT NOT NULL COMMENT '',
  `valorTotal` INT NOT NULL COMMENT '',
  `usuario` INT NOT NULL COMMENT '',
  `habitacion` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idreservas`)  COMMENT '',
  UNIQUE INDEX `idreservas_UNIQUE` (`idreservas` ASC)  COMMENT '',
  INDEX `fk_reservas_usuarios_idx` (`usuario` ASC)  COMMENT '',
  INDEX `fk_reservas_habitaciones1_idx` (`habitacion` ASC)  COMMENT '',
  CONSTRAINT `fk_reservas_usuarios`
    FOREIGN KEY (`usuario`)
    REFERENCES `hotel`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservas_habitaciones1`
    FOREIGN KEY (`habitacion`)
    REFERENCES `hotel`.`habitaciones` (`idhabitaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
